# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'TATest_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TATest_iOS
#  pod 'ThinkingSDK' #需要打开 source 'https://github.com/CocoaPods/Specs.git'
#  pod 'BMKLocationKit' #需要打开 source 'https://github.com/CocoaPods/Specs.git'
  pod 'Masonry' #不需要打开 source 'https://github.com/CocoaPods/Specs.git'
#  pod 'TATool'

  pod 'AFNetworking'
  pod 'MJExtension'

#  ENV["ThinkingSDK_source"] = '1'
#  pod 'ThinkingSDK', :path => '../../ios-sdk'
#pod 'ThinkingSDK', '2.8.1.7'
#pod 'ThinkingSDK', '2.6.5'
#  pod 'Firebase/Messaging', '8.11.0'

#  pod 'ThinkingSDK', :git=>'https://github.com/ThinkingDataAnalytics/ios-sdk.git', :branch=>'dev_2.8.0.2_fix_tpns_push'
  
#  pod 'TPNS-iOS', '1.3.4.1'

#  pod 'Adjust', '~> 4.31.0'
  pod 'ThinkingSDK', '2.8.3.1'
#pod 'ThinkingSDK', '2.7.1'
  pod 'Foggy'

end
