# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TATest_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TATest_Swift
  ENV["ThinkingSDK_source"] = '1'
  pod 'ThinkingSDK', :path => '../../ios-sdk'

end
